import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Component/Shared/NavBar";
import Footer from "@/Component/Shared/Footer";
import TimelineProvider from "@/Component/Shared/Context/TimelineProvider";
import { Toaster } from "react-hot-toast";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <NavBar></NavBar>
      
         <TimelineProvider>
           {children}
         </TimelineProvider>
        <Toaster />
        <Footer></Footer>
        </body>
    </html>
  );
}
